### PR TITLE
feat: add ordinality column to resources and representations

### PR DESCRIPTION
**Pull request by stacietaylorcima**
Hey team! All I've done here (so far) is generate the ordinality columns on the resource and representation tables. Despite that it wasn't a bunch of work, I still wanted to create a pull request so that you could all keep a finger on the pulse and quickly point out if anything is off. I'll continue to add to this pull request as I complete the request for scoping by ordinality on the resources and representations. Thanks a million!

### CODE REVIEW

**Comment by stacietaylorcima** [comment]
@flipsasser Sina had me move on to Uploading to Coyote #141 because it is a hard requirement for launching Scavenger Hunt, but ordinality was not. So, we can totally cover this stuff when we have time.

**Comment by flipsasser** [comment]
Right on. Let me know when to look at uploading!

**Comment by stacietaylorcima** [comment]
@flipsasser When you have time, will you check out my last comment on issue #141? I've run into an error that I don't know the best way to solve.

**Comment by flipsasser** [comment]
Is there a branch I can look at?

**Comment by stacietaylorcima** [comment]
@flipsasser https://github.com/coyote-team/coyote/tree/stacie/upload_aws_s3

**Comment by sinabahram** [comment]
@FlipSasser, Stacie and I had a great conversation right now.

 

Here is my recommendation for ordinality:

 

Ordinality column on resources and representations stays as is and is not respected or considered by Scavenger Hunt functionality. It’s only used for sorting in UI, API, etc.

// Stacie and Flip, please confirm whether this is fully done after Flip’s latest commits?

 

But, how do we sort clues in scavenger hunt?

 

Why don’t we just make a single additional meta: ScavengerHunt:Position or however you wish to punctuate that. all that will be is a positive integer. It’s not required, but if it exists, it’s sorted on.

 

Boom, problem solved for scavenger hunt without abusing meaning of ordinality for resources or representations.

 

Are we cool with this?

 

If so, @FlipSasser, can you make the few lines of changes necessary to do that as well as add to required cedes, etc.?

**Pull request merged**
