### PR TITLE
602 spreadsheet import failure on live

### LINKED ISSUE #602: Spreadsheet Import Failure on Live
Uploading one of the CSV files used for testing on coyote staging resulted in

> Server Error
> An unexpected error occurred. We've been notified and will work on fixing it ASAP!

The imports page lists the status of the upload as "parsing" indefinitely. Note that the CSV in question has only 10 entries.

Just including this issue to make note of the discrepancy between the functionality of staging and live.

### PR DESCRIPTION
**Pull request by jacobyarborough**

### CODE REVIEW

**Comment by jacobyarborough** [comment]
@subelsky @sinabahram here is a potential solution that I came up with. I wanted to get your input on this strategy. In the `imports controller` `create` method I am calling a method called `is_text_file?` This method checks if the user's file is a binary or not. If it is not a binary it allows the normal flow of importing, if its is a binary it renders the new page again and creates a flash alert telling the user to use a properly formatted csv file.

I chose this strategy because I couldn't create a validation on the import model to check the file, because the file was not persisted to the disk yet. So I couldn't access it in the method. I also tried the after_save and before_commit callbacks, but ran into the same issue.

If you do like this strategy I can also allow xslx files to go through, as I see in the spec for importing files, those are allowed.

**Comment by sinabahram** [comment]
Sorry, but this doesn't make sense to me. If we support .xlsx files, then we, by definition, support binary files, which invalidates the purpose of this code altogether.

**Comment by jacobyarborough** [comment]
Sina, I guess I don't understand the issue then. I guess the problem is not binary files as previously discussed. Like I stated in the slack channel, the imports process does not work for Number files, or files "changed" to csv files from numbers files instead of exporting them directly as csv on creation. That was the only way I could recreate the issue of the perpetual parsing loop for a csv file. I guess I will have to dig in a bit deeper and see what the actual issue is and why the existing error infrastructure is not working.

**Comment by sinabahram** [comment]
Let's discuss over Slack. If the issue is a clear user error, then we shouldn't have spent any of this time/cycles on fixing this as it's just not supported.

**Comment by jacobyarborough** [comment]
Not the right solution to the problem.

**Pull request closed without merging**
