### PR TITLE
Update some character casing, including COYOTE logo

### PR DESCRIPTION
**Pull request by stacietaylorcima**
This was going to be part of the PR on casing that just got merged (#249), but I didn't get to it in time. So, here it is. Small simple changes to copy.

### CODE REVIEW

**Comment by sinabahram** [comment]
The title says including the logo. Did that change actually get made or per our discussion, not get made?

**Comment by stacietaylorcima** [comment]
I originally had the logo in uppercase, then when the request to downcase everything came through I downcased it. Then you told me the logo should be uppercase so I went and uppercased it again. Did I misunderstand? The logo should be uppercase, right? @sinabahram

**Comment by sinabahram** [comment]
Haha, absolutely! Yes, it should be upper case.

**Comment by stacietaylorcima** [comment]
This is a simple PR that was good to go. So, based on a conversation with Sina where he told me during this crunch time, to not let PRs sit for more than 24 hours, I went ahead and squashed/merged. Of course, the PRs that contain important code that I am unsure about, I will leave there and just keep reminding people of code reviews. This one though was super basic code.

**Comment by flipsasser** [comment]
👍 sorry

**Pull request merged**
