### PR TITLE
Add Coyote Users

### PR DESCRIPTION
**Pull request by stacietaylorcima**
I made very small progress on this issue, but wanted to commit my updates incase anyone else took over in the meantime. I'll get back on this tonight. The sign up view is rendering but getting this error on click of submit: `No route matches [POST] "/registration.user"`

### CODE REVIEW

**Comment by stacietaylorcima** [comment]
I started on this issue because Anna had it on here Must-Fix project, but it's no longer a priority, so I'm closing this.

**Comment by sinabahram** [comment]
Understood about the change of priority, but is this being closed because it is also no longer an issue?

**Comment by stacietaylorcima** [comment]
@sinabahram The issue is still open, I just closed the Pull Request so that Flip wouldn't spend any time on it.

**Comment by stacietaylorcima** [comment]
Well, I take some of my previous message back. Anna closed the issue (#252) today because her actual issue was that she couldn't invite users. There should definitely be one open though regarding her message and all our thoughts about sign up. I'll reopen it and rename it appropriately. @sinabahram

**Pull request closed without merging**
